name: Deploy System

on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.3.0"

      - name: Install Node Dependencies
        run: npm i

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: pulumi/actions@v5
        with:
          command: up
          stack-name: dev
          config-map: "{
            tailcall-launchpad:PULUMI_ACCESS_TOKEN: { value: ${{ secrets.PULUMI_ACCESS_TOKEN }}, secret: true },
            tailcall-launchpad:AWS_ACCESS_KEY_ID: { value: ${{ secrets.AWS_ACCESS_KEY_ID }}, secret: true },
            tailcall-launchpad:AWS_SECRET_ACCESS_KEY: { value: ${{ secrets.AWS_SECRET_ACCESS_KEY }}, secret: true },
            tailcall-launchpad:AWS_REGION: { value: ${{ secrets.AWS_REGION }}, secret: true },
          }"
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}